version: "3.8"

services:
  nls-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nls-fe
    ports:
      - "8050:80"
    restart: always
    networks:
      - fe-network

networks:
  fe-network:
    external: true   # Khai báo là external để dùng chung với backend
